### PR TITLE
Friend search

### PR DESCRIPTION
**Pull request by carsonb**
We were using the game hashes before, this switches them to the nice (memory only) object for use in the GameFinder.

It then uses that finder to get the games shared by you and the selected friends! We're done!

...

...not really done.

ping @csaunders @dan-menard @davefp

### CODE REVIEW

**Comment by carsonb** [comment]
Here's a demo

**Comment by csaunders** [comment]
Most of this looks cool. My stuff will break your things, so merge your shit in and I'll fix my stuff :)

Let's wait on reviews from the other chaps

**Comment by davefp** [comment]
:+1: for use of animated gif. Will post other comments shortly

**Comment by davefp** [comment]
I'd maybe wrap the Steam API library in a service that does all that error handling bullshit so you don't have to write it again every time you use it.

This would also allow you to pull the mapping of game hashes to Game objects out of controllers and put it in the service instead.

**Comment by davefp** [comment]
:+1: :shipit:

**Pull request merged**
